//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace _2012dev4good
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CMEntities object using the connection string found in the 'CMEntities' section of the application configuration file.
        /// </summary>
        public CMEntities() : base("name=CMEntities", "CMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMEntities object.
        /// </summary>
        public CMEntities(string connectionString) : base(connectionString, "CMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMEntities object.
        /// </summary>
        public CMEntities(EntityConnection connection) : base(connection, "CMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CreativeDetail> CreativeDetails
        {
            get
            {
                if ((_CreativeDetails == null))
                {
                    _CreativeDetails = base.CreateObjectSet<CreativeDetail>("CreativeDetails");
                }
                return _CreativeDetails;
            }
        }
        private ObjectSet<CreativeDetail> _CreativeDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CreativeDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCreativeDetails(CreativeDetail creativeDetail)
        {
            base.AddObject("CreativeDetails", creativeDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMModel", Name="CreativeDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CreativeDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CreativeDetail object.
        /// </summary>
        /// <param name="cDId">Initial value of the CDId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        public static CreativeDetail CreateCreativeDetail(global::System.Int32 cDId, global::System.String userId)
        {
            CreativeDetail creativeDetail = new CreativeDetail();
            creativeDetail.CDId = cDId;
            creativeDetail.UserId = userId;
            return creativeDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CDId
        {
            get
            {
                return _CDId;
            }
            set
            {
                if (_CDId != value)
                {
                    OnCDIdChanging(value);
                    ReportPropertyChanging("CDId");
                    _CDId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CDId");
                    OnCDIdChanged();
                }
            }
        }
        private global::System.Int32 _CDId;
        partial void OnCDIdChanging(global::System.Int32 value);
        partial void OnCDIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Footer
        {
            get
            {
                return _Footer;
            }
            set
            {
                OnFooterChanging(value);
                ReportPropertyChanging("Footer");
                _Footer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Footer");
                OnFooterChanged();
            }
        }
        private global::System.String _Footer;
        partial void OnFooterChanging(global::System.String value);
        partial void OnFooterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra1
        {
            get
            {
                return _Extra1;
            }
            set
            {
                OnExtra1Changing(value);
                ReportPropertyChanging("Extra1");
                _Extra1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra1");
                OnExtra1Changed();
            }
        }
        private global::System.String _Extra1;
        partial void OnExtra1Changing(global::System.String value);
        partial void OnExtra1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra2
        {
            get
            {
                return _Extra2;
            }
            set
            {
                OnExtra2Changing(value);
                ReportPropertyChanging("Extra2");
                _Extra2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra2");
                OnExtra2Changed();
            }
        }
        private global::System.String _Extra2;
        partial void OnExtra2Changing(global::System.String value);
        partial void OnExtra2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag1
        {
            get
            {
                return _Tag1;
            }
            set
            {
                OnTag1Changing(value);
                ReportPropertyChanging("Tag1");
                _Tag1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag1");
                OnTag1Changed();
            }
        }
        private global::System.String _Tag1;
        partial void OnTag1Changing(global::System.String value);
        partial void OnTag1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag2
        {
            get
            {
                return _Tag2;
            }
            set
            {
                OnTag2Changing(value);
                ReportPropertyChanging("Tag2");
                _Tag2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag2");
                OnTag2Changed();
            }
        }
        private global::System.String _Tag2;
        partial void OnTag2Changing(global::System.String value);
        partial void OnTag2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra3
        {
            get
            {
                return _Extra3;
            }
            set
            {
                OnExtra3Changing(value);
                ReportPropertyChanging("Extra3");
                _Extra3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra3");
                OnExtra3Changed();
            }
        }
        private global::System.String _Extra3;
        partial void OnExtra3Changing(global::System.String value);
        partial void OnExtra3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra4
        {
            get
            {
                return _Extra4;
            }
            set
            {
                OnExtra4Changing(value);
                ReportPropertyChanging("Extra4");
                _Extra4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra4");
                OnExtra4Changed();
            }
        }
        private global::System.String _Extra4;
        partial void OnExtra4Changing(global::System.String value);
        partial void OnExtra4Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="loginName">Initial value of the LoginName property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.String loginName)
        {
            User user = new User();
            user.UserId = userId;
            user.LoginName = loginName;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoginName
        {
            get
            {
                return _LoginName;
            }
            set
            {
                OnLoginNameChanging(value);
                ReportPropertyChanging("LoginName");
                _LoginName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoginName");
                OnLoginNameChanged();
            }
        }
        private global::System.String _LoginName;
        partial void OnLoginNameChanging(global::System.String value);
        partial void OnLoginNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra1
        {
            get
            {
                return _Extra1;
            }
            set
            {
                OnExtra1Changing(value);
                ReportPropertyChanging("Extra1");
                _Extra1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra1");
                OnExtra1Changed();
            }
        }
        private global::System.String _Extra1;
        partial void OnExtra1Changing(global::System.String value);
        partial void OnExtra1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra2
        {
            get
            {
                return _Extra2;
            }
            set
            {
                OnExtra2Changing(value);
                ReportPropertyChanging("Extra2");
                _Extra2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra2");
                OnExtra2Changed();
            }
        }
        private global::System.String _Extra2;
        partial void OnExtra2Changing(global::System.String value);
        partial void OnExtra2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra3
        {
            get
            {
                return _Extra3;
            }
            set
            {
                OnExtra3Changing(value);
                ReportPropertyChanging("Extra3");
                _Extra3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra3");
                OnExtra3Changed();
            }
        }
        private global::System.String _Extra3;
        partial void OnExtra3Changing(global::System.String value);
        partial void OnExtra3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extra4
        {
            get
            {
                return _Extra4;
            }
            set
            {
                OnExtra4Changing(value);
                ReportPropertyChanging("Extra4");
                _Extra4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extra4");
                OnExtra4Changed();
            }
        }
        private global::System.String _Extra4;
        partial void OnExtra4Changing(global::System.String value);
        partial void OnExtra4Changed();

        #endregion
    
    }

    #endregion
    
}
